################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow_lite_lib/tensorflow/lite/micro/debug_log.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_string.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_time.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.cc \
../tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.cc 

CC_DEPS += \
./tensorflow_lite_lib/tensorflow/lite/micro/debug_log.d \
./tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_string.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_time.d \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.d \
./tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.d \
./tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.d 

OBJS += \
./tensorflow_lite_lib/tensorflow/lite/micro/debug_log.o \
./tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_string.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_time.o \
./tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.o \
./tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.o \
./tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow_lite_lib/tensorflow/lite/micro/debug_log.o: ../tensorflow_lite_lib/tensorflow/lite/micro/debug_log.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/debug_log.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.o: ../tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/memory_helpers.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_allocator.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_error_reporter.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_interpreter.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_optional_debug_tools.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_string.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_string.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_string.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_time.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_time.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_time.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.o: ../tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/micro_utils.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.o: ../tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/simple_memory_allocator.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.o: ../tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.cc tensorflow_lite_lib/tensorflow/lite/micro/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R9xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I"../tensorflow_lite_lib/tensorflow" -I"../tensorflow_lite_lib/third_party/flatbuffers/include" -I"../tensorflow_lite_lib/third_party/gemmlowp" -I"../tensorflow_lite_lib/third_party/ruy" -I"../tensorflow_lite_lib" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite_lib/tensorflow/lite/micro/test_helpers.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

